language: node_js
node_js:
  - '4.1'

env:
  global:
    - secure: "QPIRpzXvTqElZOfokkY6IEZOyMZAskZSIaWnXiIsWztHUe+r56eIZu46uopdXuSzibpX1XukTW5rM+Y8waQnekh2bZg0lg6O5Vra7iDPvZAlBMtgF+l75tEqvRCT5VqrfqbbgBEokZXJW12W1gLp7S2IQNGb6LWKuaWU8DlSHi2/jKeE6boZPQoitu9/NFvw2+4OR8/nlpB27gg0S6NlxRGLxyCstRwVUEzX5q3GfDuTV96zcpf3VHKo5+XLzN/QZ2BtQqX4zwfmTKnNeuoqFHSLDX7Iy4gUdb6Ldifz5T28KVNPsVDJk9nJPRzjLZd285OY9NMRoNvnUJJDcvy8cdhL91Bt52oIn69lAqzevtV4q0tX4YqrHl93VUyyvCKpUG+Sxgb03CthawdPFapeBl0qNy6LrppGyYeAoL3TzoWhVEMBFYrVZ0YDCbVypuRXwSyif03+ORxhjHYw6lXKnW15ZgF6YJQAUFmxmQ8i2HjEg26wPh6+/yotKT9jz8OuwdpQGTA08fxVPa47HMsobRy+NaK068BxhIzhbqDhbqcTg6HycjbnIkIyA7jv1G1bI3kiBHF97NL/rh44O8b9OQO4L27DsQ9WeRkA3L+vE11LLh1OhX6ALr26PsPS8DEdi/qA0mgPvqJIXLBpJJwUIUFcAm0Qw/4sGDooCJpZCnY="

before_install:
- gem update --system
- gem install compass
- npm install -g grunt-cli

install:
- 'npm install'

script:
- 'grunt build'

after_success:
- export GIT_DEPLOY_DIR=dist
- export GIT_DEPLOY_BRANCH=gh-pages
- export GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/ivarprudnikov/expenses-from-csv.git
- source ./deploy_to_github.sh
- echo "Done deploy.sh"

